# Importar bibliotecas necessárias

In [2]:
import pandas as pd, numpy as np, zipfile, requests, os
from io import BytesIO

In [3]:
# Crir um diretorio para amazenar o conteudo do ENEM
os.makedirs('./enem2019', exist_ok=True)

In [4]:
# Define a URL para Download
url = "https://download.inep.gov.br/microdados/microdados_enem_2019.zip"

# Faz o donload do conteudo
filebytes = BytesIO(
    requests.get(url).content
)

# Extrair o conteudo do ZIP
myzip = zipfile.ZipFile(filebytes)
myzip.extractall("./enem2019")

In [5]:
## Verificando os dados baixados

enem = pd.read_csv(
    "./enem2019/DADOS/MICRODADOS_ENEM_2019.csv",
    sep = ";",
    decimal = ".",
    encoding='Latin1'    
)

In [6]:
enem

,NU_INSCRICAO,NU_ANO,CO_MUNICIPIO_RESIDENCIA,NO_MUNICIPIO_RESIDENCIA,CO_UF_RESIDENCIA,SG_UF_RESIDENCIA,NU_IDADE,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,...,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023,Q024,Q025
0,190001004627,2019,1506807,Santarém,15,PA,21,M,1,3,...,A,A,A,C,B,A,D,A,B,A
1,190001004628,2019,1504059,Mãe do Rio,15,PA,16,F,1,3,...,A,A,A,B,B,A,B,A,A,A
2,190001004629,2019,1505502,Paragominas,15,PA,18,F,1,1,...,B,A,A,D,B,B,D,A,C,B
3,190001004630,2019,1507706,São Sebastião da Boa Vista,15,PA,23,M,0,3,...,A,A,A,C,A,A,D,A,A,A
4,190001004631,2019,1503903,Juruti,15,PA,23,M,1,3,...,A,A,A,B,A,A,D,A,A,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5095265,190006129589,2019,2928604,Santo Amaro,29,BA,28,F,2,2,...,A,A,A,B,A,A,B,A,A,B
5095266,190006129590,2019,2927408,Salvador,29,BA,25,M,1,2,...,A,A,A,A,A,A,B,A,A,A
5095267,190006129591,2019,2931806,Tremedal,29,BA,18,F,1,3,...,A,A,A,B,A,A,B,A,A,B
5095268,190006129592,2019,2927408,Salvador,29,BA,16,M,1,1,...,B,A,A,B,B,A,C,A,B,B
5095269,190006129593,2019,2914802,Itabuna,29,BA,25,F,1,2,...,B,A,B,B,B,A,B,A,B,B

In [7]:
enem.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5095270 entries, 0 to 5095269
Columns: 136 entries, NU_INSCRICAO to Q025
dtypes: float64(24), int64(71), object(41)
memory usage: 5.2+ GB

In [8]:
## verificar o dicionario dos dados
dict(enem.dtypes)

{'NU_INSCRICAO': dtype('int64'),
 'NU_ANO': dtype('int64'),
 'CO_MUNICIPIO_RESIDENCIA': dtype('int64'),
 'NO_MUNICIPIO_RESIDENCIA': dtype('O'),
 'CO_UF_RESIDENCIA': dtype('int64'),
 'SG_UF_RESIDENCIA': dtype('O'),
 'NU_IDADE': dtype('int64'),
 'TP_SEXO': dtype('O'),
 'TP_ESTADO_CIVIL': dtype('int64'),
 'TP_COR_RACA': dtype('int64'),
 'TP_NACIONALIDADE': dtype('int64'),
 'CO_MUNICIPIO_NASCIMENTO': dtype('float64'),
 'NO_MUNICIPIO_NASCIMENTO': dtype('O'),
 'CO_UF_NASCIMENTO': dtype('float64'),
 'SG_UF_NASCIMENTO': dtype('O'),
 'TP_ST_CONCLUSAO': dtype('int64'),
 'TP_ANO_CONCLUIU': dtype('int64'),
 'TP_ESCOLA': dtype('int64'),
 'TP_ENSINO': dtype('float64'),
 'IN_TREINEIRO': dtype('int64'),
 'CO_ESCOLA': dtype('float64'),
 'CO_MUNICIPIO_ESC': dtype('float64'),
 'NO_MUNICIPIO_ESC': dtype('O'),
 'CO_UF_ESC': dtype('float64'),
 'SG_UF_ESC': dtype('O'),
 'TP_DEPENDENCIA_ADM_ESC': dtype('float64'),
 'TP_LOCALIZACAO_ESC': dtype('float64'),
 'TP_SIT_FUNC_ESC': dtype('float64'),
 'IN_BAIXA_VISAO': dtype('int64'),
 'IN_CEGUEIRA': dtype('int64'),
 'IN_SURDEZ': dtype('int64'),
 'IN_DEFICIENCIA_AUDITIVA': dtype('int64'),
 'IN_SURDO_CEGUEIRA': dtype('int64'),
 'IN_DEFICIENCIA_FISICA': dtype('int64'),
 'IN_DEFICIENCIA_MENTAL': dtype('int64'),
 'IN_DEFICIT_ATENCAO': dtype('int64'),
 'IN_DISLEXIA': dtype('int64'),
 'IN_DISCALCULIA': dtype('int64'),
 'IN_AUTISMO': dtype('int64'),
 'IN_VISAO_MONOCULAR': dtype('int64'),
 'IN_OUTRA_DEF': dtype('int64'),
 'IN_GESTANTE': dtype('int64'),
 'IN_LACTANTE': dtype('int64'),
 'IN_IDOSO': dtype('int64'),
 'IN_ESTUDA_CLASSE_HOSPITALAR': dtype('int64'),
 'IN_SEM_RECURSO': dtype('int64'),
 'IN_BRAILLE': dtype('int64'),
 'IN_AMPLIADA_24': dtype('int64'),
 'IN_AMPLIADA_18': dtype('int64'),
 'IN_LEDOR': dtype('int64'),
 'IN_ACESSO': dtype('int64'),
 'IN_TRANSCRICAO': dtype('int64'),
 'IN_LIBRAS': dtype('int64'),
 'IN_TEMPO_ADICIONAL': dtype('int64'),
 'IN_LEITURA_LABIAL': dtype('int64'),
 'IN_MESA_CADEIRA_RODAS': dtype('int64'),
 'IN_MESA_CADEIRA_SEPARADA': dtype('int64'),
 'IN_APOIO_PERNA': dtype('int64'),
 'IN_GUIA_INTERPRETE': dtype('int64'),
 'IN_COMPUTADOR': dtype('int64'),
 'IN_CADEIRA_ESPECIAL': dtype('int64'),
 'IN_CADEIRA_CANHOTO': dtype('int64'),
 'IN_CADEIRA_ACOLCHOADA': dtype('int64'),
 'IN_PROVA_DEITADO': dtype('int64'),
 'IN_MOBILIARIO_OBESO': dtype('int64'),
 'IN_LAMINA_OVERLAY': dtype('int64'),
 'IN_PROTETOR_AURICULAR': dtype('int64'),
 'IN_MEDIDOR_GLICOSE': dtype('int64'),
 'IN_MAQUINA_BRAILE': dtype('int64'),
 'IN_SOROBAN': dtype('int64'),
 'IN_MARCA_PASSO': dtype('int64'),
 'IN_SONDA': dtype('int64'),
 'IN_MEDICAMENTOS': dtype('int64'),
 'IN_SALA_INDIVIDUAL': dtype('int64'),
 'IN_SALA_ESPECIAL': dtype('int64'),
 'IN_SALA_ACOMPANHANTE': dtype('int64'),
 'IN_MOBILIARIO_ESPECIFICO': dtype('int64'),
 'IN_MATERIAL_ESPECIFICO': dtype('int64'),
 'IN_NOME_SOCIAL': dtype('int64'),
 'CO_MUNICIPIO_PROVA': dtype('int64'),
 'NO_MUNICIPIO_PROVA': dtype('O'),
 'CO_UF_PROVA': dtype('int64'),
 'SG_UF_PROVA': dtype('O'),
 'TP_PRESENCA_CN': dtype('int64'),
 'TP_PRESENCA_CH': dtype('int64'),
 'TP_PRESENCA_LC': dtype('int64'),
 'TP_PRESENCA_MT': dtype('int64'),
 'CO_PROVA_CN': dtype('float64'),
 'CO_PROVA_CH': dtype('float64'),
 'CO_PROVA_LC': dtype('float64'),
 'CO_PROVA_MT': dtype('float64'),
 'NU_NOTA_CN': dtype('float64'),
 'NU_NOTA_CH': dtype('float64'),
 'NU_NOTA_LC': dtype('float64'),
 'NU_NOTA_MT': dtype('float64'),
 'TX_RESPOSTAS_CN': dtype('O'),
 'TX_RESPOSTAS_CH': dtype('O'),
 'TX_RESPOSTAS_LC': dtype('O'),
 'TX_RESPOSTAS_MT': dtype('O'),
 'TP_LINGUA': dtype('int64'),
 'TX_GABARITO_CN': dtype('O'),
 'TX_GABARITO_CH': dtype('O'),
 'TX_GABARITO_LC': dtype('O'),
 'TX_GABARITO_MT': dtype('O'),
 'TP_STATUS_REDACAO': dtype('float64'),
 'NU_NOTA_COMP1': dtype('float64'),
 'NU_NOTA_COMP2': dtype('float64'),
 'NU_NOTA_COMP3': dtype('float64'),
 'NU_NOTA_COMP4': dtype('float64'),
 'NU_NOTA_COMP5': dtype('float64'),
 'NU_NOTA_REDACAO': dtype('float64'),
 'Q001': dtype('O'),
 'Q002': dtype('O'),
 'Q003': dtype('O'),
 'Q004': dtype('O'),
 'Q005': dtype('int64'),
 'Q006': dtype('O'),
 'Q007': dtype('O'),
 'Q008': dtype('O'),
 'Q009': dtype('O'),
 'Q010': dtype('O'),
 'Q011': dtype('O'),
 'Q012': dtype('O'),
 'Q013': dtype('O'),
 'Q014': dtype('O'),
 'Q015': dtype('O'),
 'Q016': dtype('O'),
 'Q017': dtype('O'),
 'Q018': dtype('O'),
 'Q019': dtype('O'),
 'Q020': dtype('O'),
 'Q021': dtype('O'),
 'Q022': dtype('O'),
 'Q023': dtype('O'),
 'Q024': dtype('O'),
 'Q025': dtype('O')}

In [17]:
# Tabela cruzada
# Contar quantos alunos por estado
enem.SG_UF_ESC.value_counts() / enem.shape[0]

SP    0.043065
CE    0.022043
MG    0.021230
RJ    0.014344
BA    0.013803
PE    0.012071
PR    0.010360
PA    0.009174
RS    0.009062
MA    0.008537
GO    0.006976
SC    0.006800
PB    0.005287
AM    0.005067
ES    0.004989
PI    0.004741
DF    0.004136
RN    0.003994
MT    0.003537
AL    0.003445
MS    0.003050
SE    0.002648
RO    0.002369
TO    0.001783
AP    0.001204
AC    0.001046
RR    0.000432
Name: SG_UF_ESC, dtype: float64

In [18]:
# Filtrar apenas os alunos de Minas Gerais
enem.loc[
    enem.SG_UF_ESC == 'MG'
]

,NU_INSCRICAO,NU_ANO,CO_MUNICIPIO_RESIDENCIA,NO_MUNICIPIO_RESIDENCIA,CO_UF_RESIDENCIA,SG_UF_RESIDENCIA,NU_IDADE,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,...,Q017,Q018,Q019,Q020,Q021,Q022,Q023,Q024,Q025,Média das Notas
59032,190001063661,2019,1508357,Vitória do Xingu,15,PA,17,F,1,2,...,A,A,B,A,A,D,A,A,A,NaN
215279,190001219912,2019,3144656,Ninheira,31,MG,18,F,1,1,...,A,A,B,A,A,B,B,A,A,NaN
215402,190001220035,2019,3102704,Cachoeira de Pajeú,31,MG,18,F,1,3,...,A,A,B,A,B,C,A,A,B,NaN
215683,190001220316,2019,3106200,Belo Horizonte,31,MG,17,F,1,1,...,A,B,B,A,B,E,B,C,B,NaN
215690,190001220323,2019,3139607,Mantena,31,MG,17,M,1,2,...,A,A,C,A,A,D,A,B,B,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5095243,190006120169,2019,3169406,Três Pontas,31,MG,18,F,1,1,...,A,A,C,B,B,D,B,B,B,NaN
5095245,190006120171,2019,3106705,Betim,31,MG,24,F,1,3,...,A,A,B,B,A,B,A,A,A,NaN
5095248,190006120174,2019,3131901,Itabirito,31,MG,18,F,1,2,...,A,B,E,B,B,E,B,C,B,NaN
5095250,190006120176,2019,3170206,Uberlândia,31,MG,18,F,1,3,...,A,A,B,A,A,E,A,B,B,NaN
5095251,190006120177,2019,3162708,São João do Paraíso,31,MG,17,F,1,3,...,A,A,B,A,A,E,A,B,B,NaN

In [19]:
# Exportar os dados para um arquivo CSV apenas com alunos de Minas Gerais
enem.loc[
    enem.SG_UF_ESC == 'MG'
].to_csv('enem2019_MG.csv')

In [20]:

# 1-Qual é a média da nota em matemática de todos os alunos mineiros?
enem.loc[
    enem.SG_UF_RESIDENCIA == 'MG'
].NU_NOTA_MT.mean()

546.7962076512125

In [37]:
# 2-Qual é a média da nota em Linguagens e Códigos de todos os alunos mineiros?
enem.loc[
    enem.SG_UF_RESIDENCIA == 'MG'
].NU_NOTA_LC.mean()

531.2155500475544

In [24]:
# 3-Qual é a média da nota em Ciências Humanas dos alunos do sexo FEMININO mineiros?
enem.loc[
    (enem.SG_UF_RESIDENCIA == 'MG') &
    (enem.TP_SEXO == 'F'),
    'NU_NOTA_CH',
].mean()

515.1270983575349

In [25]:
# 4-Qual é a média da nota em Ciências Humanas dos alunos do sexo MASCULINO?
enem.loc[
    (enem.SG_UF_RESIDENCIA == 'MG') &
    (enem.TP_SEXO == 'M'),
    'NU_NOTA_CH',
].mean()

529.6982704731574

In [26]:
# 5-Qual é a média da nota em Matemática dos alunos do sexo FEMININO que moram na cidade de Montes Claros?
enem.loc[
    (enem.SG_UF_RESIDENCIA =="MG") &
    (enem.NO_MUNICIPIO_RESIDENCIA =="Montes Claros") &
    (enem.TP_SEXO =="F"),
    "NU_NOTA_MT"
].mean()

525.4776724249901

In [27]:
# 6-Qual é a média da nota em Matemática dos alunos do município de Sabará que possuem TV por assinatura na residência?
enem.loc[ 
    (enem.SG_UF_RESIDENCIA =="MG") &
    (enem.NO_MUNICIPIO_RESIDENCIA =="Sabará") &
    (enem.Q021 == "B"),
    "NU_NOTA_MT"
].mean()

543.2927556818183

In [28]:
# 7-Qual é a média da nota em Ciências Humanas dos alunos mineiros que possuem dois fornos micro-ondas em casa?
enem.loc[
    (enem.SG_UF_RESIDENCIA =="MG") &
    (enem.Q016 == "C"),
    "NU_NOTA_CH"
].mean()

557.2765986394558

In [29]:
# 8-Qual é a nota média em Matemática dos alunos mineiros cuja mãe completou a pós-graduação?
enem.loc[
    (enem.SG_UF_RESIDENCIA =="MG") &
    (enem.Q002 == "G"),
    "NU_NOTA_MT"
].mean()

620.007062070985

In [30]:
# 9-Qual é a nota média em Matemática dos alunos de Belo Horizonte e de Conselheiro Lafaiete?
enem.loc[
    (enem.SG_UF_RESIDENCIA =="MG") &
    (enem.NO_MUNICIPIO_RESIDENCIA.isin(['Belo Horizonte','Conselheiro Lafaiete'])),
    "NU_NOTA_MT"
].mean()

578.0392265100068

In [31]:
# 10-Qual é a nota média em Ciências Humanas dos alunos mineiros que moram sozinhos?
enem.loc[
    (enem.SG_UF_RESIDENCIA =="MG") &
    (enem.Q005 == 1),
    "NU_NOTA_CH"
].mean()

534.4573388609205

In [32]:
# 11-Qual é a nota média em Ciências Humanas dos alunos mineiros cujo pai completou pós-graduação e possuem renda familiar entre R$ 8.982,01 e R$ 9.980,00.
enem.loc[
    (enem.SG_UF_RESIDENCIA =="MG") &
    (enem.Q001 == "G") &
    (enem.Q006 == "M"),
    "NU_NOTA_CH"
].mean()

586.7231663685159

In [33]:
# 12-Qual é a nota média em Matemática dos alunos do sexo Feminino que moram em Lavras e escolheram “Espanhol” como língua estrangeira?
enem.loc[
    (enem.SG_UF_RESIDENCIA =="MG") &
    (enem.TP_SEXO =="F") &
    (enem.NO_MUNICIPIO_RESIDENCIA.isin(['Lavras'])) &
    (enem.TP_LINGUA ==1),
    "NU_NOTA_MT"
].mean()

510.80950782997775

In [34]:
# 13-Qual é a nota média em Matemática dos alunos do sexo Masculino que moram em Ouro Preto?
enem.loc[
    (enem.SG_UF_RESIDENCIA =="MG") &
    (enem.TP_SEXO =="M") &
    (enem.NO_MUNICIPIO_RESIDENCIA.isin(['Ouro Preto'])),
    "NU_NOTA_MT"
].mean()

555.0832520325198

In [35]:
# 14-Qual é a nota média em Ciências Humanas dos alunos surdos?
enem.loc[
    (enem.SG_UF_RESIDENCIA =="MG") &
    (enem.IN_SURDEZ ==1),
    "NU_NOTA_CH"
].mean()

435.38796296296283

In [36]:
# 15-Qual é a nota média em Matemática dos alunos do sexo FEMININO, que moram em Belo Horizonte, Sabará, Nova Lima e Betim e possuem dislexia?
enem.loc[
    (enem.SG_UF_RESIDENCIA =="MG") &
    (enem.TP_SEXO =="F") &
    (enem.NO_MUNICIPIO_RESIDENCIA.isin(['Belo Horizonte','Sabará','Nova Lima','Betim'])) &
    (enem.IN_DISLEXIA ==1),
    "NU_NOTA_MT"
].mean()

582.1935483870968